baseURL = "http://en.littlefrenchescape-9iti.temp-dns.com/"
languageCode = "en-us"
title = "Rossignols Gite"
theme = "rossignols"

defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
name = "Our Gite"
url = "/the-gite/"
weight = 20

[[languages.en.menu.main]]
name = "Things to do"
url = "/things-to-do/"
weight = 30

[[languages.en.menu.main]]
name = "Find us"
url = "/find-us/"
weight = 40


[languages.fr]
weight = 10
languageName = "French"

[[languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 10

[[languages.fr.menu.main]]
name = "Notre Gite"
url = "/the-gite/"
weight = 20

[[languages.fr.menu.main]]
name = "Voir et faire"
url = "/things-to-do/"
weight = 30

[[languages.fr.menu.main]]
name = "Trouvez nous"
url = "/find-us/"
weight = 40
