baseURL = "http://en.littlefrenchescape-9iti.temp-dns.com/"
languageCode = "en-us"
title = "Rossignols Gite"
theme = "rossignols"
[languages]
  [languages.en]
    baseURL = "http://en.littlefrenchescape-9iti.temp-dns.com/"
    languageName = "English"
    title = "In English"
    weight = 1
  [languages.fr]
    baseURL = "http://fr.littlefrenchescape-9iti.temp-dns.com/"
    languageName = "Français"
    title = "En Français"
    weight = 2
